### ISSUE TITLE
Error: module curses has no attribute A_ITALIC

### ISSUE THREAD

**Issue by reportaman** [wustho/epy#40]
When I open a epub or mobi, I get the following error. I have not updated epy in my other machine, this does not happen there. Am using the current version of pip3 while reporting this on my current machine.

```
❯ epy ~/Desktop/Books/Effective_Writing.epub
Traceback (most recent call last):
  File "/opt/homebrew/bin/epy", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/epy.py", line 3358, in main
    curses.wrapper(preread, filepath)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/opt/homebrew/lib/python3.9/site-packages/epy.py", line 3215, in preread
    reading_state = reader.read(reading_state)
  File "/opt/homebrew/lib/python3.9/site-packages/epy.py", line 2501, in read
    text_structure = parse_html(
  File "/opt/homebrew/lib/python3.9/site-packages/epy.py", line 1407, in parse_html
    return parser.get_structured_text(textwidth, starting_line)
  File "/opt/homebrew/lib/python3.9/site-packages/epy.py", line 831, in get_structured_text
    attr=curses.A_ITALIC,
AttributeError: module 'curses' has no attribute 'A_ITALIC'

```

**Comment by wustho** [comment]
Hello there, current version of epy only supported for python 3.7 or above which support curses and stuff... So really sorry for this, you might need to use older version of epy

**Comment by reportaman** [comment]
@wustho I am using python 3.9.8. I checked that on my system python pointed to version ``2.something``, so aliased python to python3, but I still get the same error.

**Comment by wustho** [comment]
@reportaman this is weird... I just read your traceback more thoroughly, and it is indeed using correct python version... So indeed as you guessed, the issue is within the epy, it should handle unavailable italic... I will fix it soon... Thanks for detailed traceback btw.

**Comment by wustho** [comment]
@reportaman Hey there just fixed this in `v2021.12.18`, you can upgrade it via `pip`. And let me know if the issue still persists... Thanks

**Comment by mcepl** [comment]
Ping? Any update here or was the issue solved?
