### ISSUE TITLE
error: do not load epub file

### ISSUE THREAD

**Issue by buribu** [wustho/epy#5]
Python 3.8.2   
pip 20.0.2

epy "anyfile.epy"

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/epy", line 11, in <module>
    load_entry_point('epy==2020.3.8', 'console_scripts', 'epy')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/epy.py", line 1213, in main
    loadstate()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/epy.py", line 523, in loadstate
    STATE = json.load(f)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 12 column 9 (char 435)

**Comment by wustho** [comment]
Hey there, how long have you been using epy? Did you just update recently?

**Comment by buribu** [comment]
I used fbless.
https://github.com/ashinkarov/fbless
But this module has two drawbacks ...
1. This module was written for python 2
2. This module is an ebook reader for the fb2 format.
I had to convert my ebooks.
And keep two versions of python installed.

Yes, the problem happened in the current version of epy. I'm using epr or epy to simplify things ... epr is working now.

**Comment by wustho** [comment]
Hey there, seems like I did some patching without thinking about backward compatibility, since I thought a lot more people using epr than epy...

Can you delete recursively directory `~/.config/epy`... And try `epy epubfile.epub`and see if the problem still persists?

**Comment by buribu** [comment]
Ok. Now it's working. Thanks.
