### ISSUE TITLE
Invalid search regex crashes the program with a traceback

### ISSUE THREAD

**Issue by ghost** [wustho/epy#7]
I've accidentally hit enter after /? and the program crashed with the following traceback:

    Traceback (most recent call last):
      File "/usr/bin/epy", line 11, in <module>
        load_entry_point('epy==2020.4.17', 'console_scripts', 'epy')()
      File "/usr/lib64/python3.7/site-packages/epy.py", line 1437, in main
        curses.wrapper(preread, file)
      File "/usr/lib64/python3.7/curses/__init__.py", line 94, in wrapper
        return func(stdscr, *args, **kwds)
      File "/usr/lib64/python3.7/site-packages/epy.py", line 1336, in preread
        ebook, idx, width, y, pctg, sec
      File "/usr/lib64/python3.7/site-packages/epy.py", line 1159, in reader
        index, len(contents)
      File "/usr/lib64/python3.7/site-packages/epy.py", line 832, in searching
        pattern = re.compile(SEARCHPATTERN[1:], re.IGNORECASE)
      File "/usr/lib64/python3.7/re.py", line 234, in compile
        return _compile(pattern, flags)
      File "/usr/lib64/python3.7/re.py", line 286, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/lib64/python3.7/sre_compile.py", line 764, in compile
        p = sre_parse.parse(p, flags)
      File "/usr/lib64/python3.7/sre_parse.py", line 930, in parse
        p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
      File "/usr/lib64/python3.7/sre_parse.py", line 426, in _parse_sub
        not nested and not items))
      File "/usr/lib64/python3.7/sre_parse.py", line 651, in _parse
        source.tell() - here + len(this))
    re.error: nothing to repeat at position 0

You should probably catch this exception and instead display a relevant error message about an invalid regexp search string.

It's not a critical bug, yet epy seems to lose the current position in the file when crashing like that. Without looking at the code, I can assume it only saves position when exitting gracefully.

**Comment by wustho** [comment]
Thanks so much for the advice mate, will fix it later...

**Comment by wustho** [comment]
Oh actually it's possible to catch all exception

**Comment by wustho** [comment]
Sorry accidentally pressing close and comment issue

**Comment by wustho** [comment]
Just like you said, it is indeed possible to catch every exception and save reading state after... But bare try-except without specific exception will catch `sys.exit("asd")` as an error, which is my favorite way of debugging... So I guess I will only make epy catch re.error tomorrow

**Comment by wustho** [comment]
Hey there just fixed this: https://github.com/wustho/epy/commit/3349f99ed28b5c9884308fba969e7ec554a60415

**Comment by somospocos** [comment]
Reinstalled the latest version and everything is fine now, thank you.
