### ISSUE TITLE
Valid EPub breaks epy: ERROR: Badly-structured ebook. "There is no item named 'OEBPS/../OEBPF/navigation.ncx' in the archive"

### ISSUE THREAD

**Issue by mcepl** [wustho/epy#93]
[One Week Late by Bethany Delleman.zip](https://github.com/wustho/epy/files/11712000/One.Week.Late.by.Bethany.Delleman.zip) (renamed to `.zip` for GitHub).

EPubCheck (5.0.0) doesn’t anything wrong with this file (and any other EPub validators I can find online), but

```sh
 $ epy /tmp/One\ Week\ Late\ by\ Bethany\ Delleman.epub
ERROR: Badly-structured ebook.
"There is no item named 'OEBPS/../OEBPF/navigation.ncx' in the archive"
 $
```

**Comment by mcepl** [comment]
With `DEBUG=True` I get:

```python
Traceback (most recent call last):
  File "/home/matej/.local/bin/epy", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/matej/archiv/2024/projekty/epy/src/epy_reader/__main__.py", line 18, in main
    filepath = curses.wrapper(reader.start_reading, filepath)
  File "/usr/lib64/python3.13/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/matej/archiv/2024/projekty/epy/src/epy_reader/reader.py", line 1610, in start_reading
    reader = Reader(screen=stdscr, ebook=ebook, config=config, state=state)
  File "/home/matej/archiv/2024/projekty/epy/src/epy_reader/reader.py", line 105, in __init__
    raise e
  File "/home/matej/archiv/2024/projekty/epy/src/epy_reader/reader.py", line 101, in __init__
    self.ebook.initialize()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/matej/archiv/2024/projekty/epy/src/epy_reader/ebooks/epub.py", line 173, in initialize
    toc = ET.parse(self.file.open(toc_path)).getroot()
                   ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.13/zipfile/__init__.py", line 1639, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python3.13/zipfile/__init__.py", line 1567, in getinfo
    raise KeyError(
        'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'OEBPS/../OEBPF/navigation.ncx' in the archive"
```
